//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "facet")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub key: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub header_field_name: String,
    #[sea_orm(column_type = "Text")]
    pub facet_address_type: String,
    #[sea_orm(has_one)]
    pub in_note_address: HasOne<super::in_note_address::Entity>,
    #[sea_orm(has_many)]
    pub number_facet_fields: HasMany<super::number_facet_field::Entity>,
    #[sea_orm(has_one)]
    pub shard_address: HasOne<super::shard_address::Entity>,
    #[sea_orm(has_many)]
    pub text_facet_fields: HasMany<super::text_facet_field::Entity>,
    #[sea_orm(has_many)]
    pub timestamp_facet_fields: HasMany<super::timestamp_facet_field::Entity>,
    #[sea_orm(has_many)]
    pub toggle_facet_fields: HasMany<super::toggle_facet_field::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
