//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "shard_address")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub shard_key: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub address_for: String,
    #[sea_orm(unique)]
    pub facet_key: Option<i64>,
    #[sea_orm(unique)]
    pub note_key: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "facet_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub facet: HasOne<super::facet::Entity>,
    #[sea_orm(
        belongs_to,
        from = "note_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub note: HasOne<super::note::Entity>,
    #[sea_orm(
        belongs_to,
        from = "shard_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub shard: HasOne<super::shard::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
