//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "shard")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub key: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(unique)]
    pub parent_shard_key: Option<i64>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_shard_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub shard: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub shard_addresses: HasMany<super::shard_address::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
