//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fs_adresses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub node_key: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub extension: String,
    #[sea_orm(column_type = "Text")]
    pub fs_address_for: String,
    #[sea_orm(column_type = "Blob", nullable)]
    pub raw_file_data: Option<Vec<u8>>,
    #[sea_orm(unique)]
    pub note_key: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "node_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub fs_nodes: HasOne<super::fs_nodes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
