//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fs_nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub key: i64,
    #[sea_orm(unique)]
    pub id: String,
    #[sea_orm(unique)]
    pub name: String,
    pub creation_time: Option<DateTime>,
    pub last_acess: Option<DateTime>,
    pub last_modf: Option<DateTime>,
    pub last_node_change: Option<DateTime>,
    pub parent_node_key: Option<i64>,
    #[sea_orm(has_many)]
    pub fs_adresses: HasMany<super::fs_adresses::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_node_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub fs_nodes: HasOne<Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
