//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fs_node_generation")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub node_key: i64,
    pub generation: i64,
}

impl ActiveModelBehavior for ActiveModel {}
