//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "in_note_addresses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub note_key: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub col_start: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub line_start: i64,
    pub col_width: Option<i64>,
    pub lines_amount: i64,
    #[sea_orm(unique)]
    pub facet_key: i64,
    #[sea_orm(
        belongs_to,
        from = "facet_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub facets: HasOne<super::facets::Entity>,
    #[sea_orm(
        belongs_to,
        from = "note_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub notes: HasOne<super::notes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
