//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod facet;
pub mod fs_adress;
pub mod fs_node;
pub mod fs_node_generation;
pub mod in_note_address;
pub mod note;
pub mod number_facet_field;
pub mod shard;
pub mod shard_address;
pub mod text_facet_field;
pub mod timestamp_facet_field;
pub mod toggle_facet_field;
