//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod facets;
pub mod fs_adresses;
pub mod fs_nodes;
pub mod in_note_addresses;
pub mod notes;
pub mod number_facet_field;
pub mod shard_addresses;
pub mod shards;
pub mod text_facet_field;
pub mod timestamp_facet_field;
pub mod toggle_facet_field;
