//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "number_facet_field")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub facet_key: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Float")]
    pub value: f32,
    #[sea_orm(
        belongs_to,
        from = "facet_key",
        to = "key",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub facet: HasOne<super::facet::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
